# Generated by Django 5.0.8 on 2026-03-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_collection_collectionbook_collection_books'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created_at'], 'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AddField(
            model_name='book',
            name='date_finished',
            field=models.DateField(blank=True, help_text='Когда закончили читать', null=True, verbose_name='Дата окончания чтения'),
        ),
        migrations.AddField(
            model_name='book',
            name='date_started',
            field=models.DateField(blank=True, help_text='Когда начали читать', null=True, verbose_name='Дата начала чтения'),
        ),
    ]
