# Generated by Django 5.0.8 on 2026-03-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_book_options_book_date_finished_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='format',
            field=models.CharField(blank=True, choices=[('paper', 'Бумажная'), ('ebook', 'Электронная'), ('audio', 'Аудио')], max_length=10, null=True, verbose_name='Формат'),
        ),
        migrations.AddField(
            model_name='book',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Личные заметки'),
        ),
        migrations.AddField(
            model_name='book',
            name='series',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Серия'),
        ),
        migrations.AddField(
            model_name='book',
            name='series_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер в серии'),
        ),
    ]
