# Generated by Django 5.0.8 on 2026-06-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_author_name_alter_genre_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='quotes',
            field=models.TextField(blank=True, null=True, verbose_name='Цитаты из книги'),
        ),
    ]
