# Generated by Django 5.0.8 on 2026-06-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_book_quotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='mood',
            field=models.CharField(blank=True, choices=[('😢', 'Грустная'), ('😂', 'Смешная'), ('🤯', 'Шокирующая'), ('🥰', 'Уютная'), ('🔥', 'Захватывающая'), ('🤔', 'Заставляет думать'), ('🎯', 'Полезная'), ('😌', 'Успокаивающая'), ('🤬', 'Бесила'), ('🎨', 'Визуально красивая')], max_length=5, null=True, verbose_name='Настроение от книги'),
        ),
    ]
