# Generated by Django 5.0.8 on 2026-06-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_book_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='music_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название трека'),
        ),
        migrations.AddField(
            model_name='book',
            name='music_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на музыку'),
        ),
        migrations.AddField(
            model_name='book',
            name='total_reading_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='mood',
            field=models.CharField(blank=True, choices=[('sad', 'Грустная'), ('funny', 'Смешная'), ('shocking', 'Шокирующая'), ('cozy', 'Уютная'), ('exciting', 'Захватывающая'), ('thoughtful', 'Заставляет думать'), ('useful', 'Полезная'), ('calming', 'Успокаивающая'), ('angry', 'Бесила'), ('beautiful', 'Визуально красивая')], max_length=20, null=True, verbose_name='Настроение от книги'),
        ),
    ]
