# Generated by Django 5.0.8 on 2026-06-13 20:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_book_music_title_book_music_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='total_reading_minutes',
        ),
        migrations.AddField(
            model_name='book',
            name='total_reading_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='Общее время чтения (сек)'),
        ),
        migrations.CreateModel(
            name='ReadingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='catalog.book')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
